export const listMenusEndpoint = {
    method: "GET",
    path: "/api/v1/menus",
    name: "List Menus",
    auth: true,
    description:
        "Return menu hierarchy filtered by the authenticated user's permissions. Each menu item includes a unique code for role-based access control (RBAC).",
    payload: "None",
    response: "200 MenuCollection",
    methodClass: "bg-sky-100 text-sky-700",
    parameters: [],
    requestExample: null,
    schemaExample: null,
    responses: [
        {
            code: 200,
            description: "Filtered menu hierarchy",
            example: {
                success: true,
                data: [
                    {
                        id: 1,
                        code: "M00",
                        name: "Dashboard",
                        icon: "home",
                        href: "/dashboard",
                        order: 1,
                        is_active: true,
                        full_code: "M00",
                        submenus: [],
                    },
                    {
                        id: 2,
                        code: "M01",
                        name: "Master Data",
                        icon: "database",
                        href: null,
                        order: 2,
                        is_active: true,
                        full_code: "M01",
                        submenus: [
                            {
                                id: 1,
                                main_menu_id: 2,
                                code: "S01",
                                name: "Business Partner",
                                href: null,
                                order: 1,
                                is_active: true,
                                full_code: "M01.S01",
                                child_menus: [
                                    {
                                        id: 1,
                                        submenu_id: 1,
                                        code: "C01",
                                        name: "Customer",
                                        href: "/dashboard/master-data/customer",
                                        order: 1,
                                        is_active: true,
                                        full_code: "M01.S01.C01",
                                        hierarchy: {
                                            main: "M01",
                                            sub: "S01",
                                            child: "C01",
                                            fullCode: "M01.S01.C01",
                                        },
                                    },
                                ],
                            },
                            {
                                id: 2,
                                main_menu_id: 2,
                                code: "S02",
                                name: "Inventory",
                                href: null,
                                order: 2,
                                is_active: true,
                                full_code: "M01.S02",
                                child_menus: [
                                    {
                                        id: 5,
                                        submenu_id: 2,
                                        code: "C01",
                                        name: "Item Master",
                                        href: "/dashboard/master-data/item-master",
                                        order: 1,
                                        is_active: true,
                                        full_code: "M01.S02.C01",
                                        hierarchy: {
                                            main: "M01",
                                            sub: "S02",
                                            child: "C01",
                                            fullCode: "M01.S02.C01",
                                        },
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
        },
        {
            code: 401,
            description: "Unauthenticated",
            example: { message: "Unauthenticated." },
        },
    ],
};
